Modules/Sap/Http/routes.php
<?php

Route::group(['middleware' => 'web', 'namespace' => 'Modules\Sap\Http\Controllers'], function()
{
    Route::resource('saps', 'SapsController');
});

Modules/Sap/Entities/Sap.php
<?php

namespace Modules\Sap\Entities;

use Illuminate\Database\Eloquent\Model;
use App\User;

class Sap extends Model
{
    protected $fillable = ['name','code'];

    public function users(){
        return $this->belongsToMany(User::class);
    }
}

Modules/Sap/Http/Controllers/SapsController.php
<?php

namespace Modules\Sap\Http\Controllers;


use App\Authorizable;
use Session;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Modules\Sap\Repositories\SapsRepository as SR;
use Modules\Sap\Http\Requests\SapsCreateRequest as SCR;
use App\Http\Controllers\Controller;

class SapsController extends Controller
{
    use Authorizable;

    private $entity;
    protected $model;

    public function __construct(){
        $this->entity = 'SAP Module';                     
    }

    public function index(SR $repo){
        $results = $repo->all();
        return view('sap::index',compact('results'));
    }

    public function create(){
        return view('sap::form');
    }

    public function show(){

    }

    public function store(SCR $request, SR $repo)
    {
        $repo->create(['name'=>$request->name,'code'=>$request->code]);
        Session::flash('success', 'The '.$this->entity.' has been created successfully');
        return redirect()->route('saps.index');
    }

    public function edit(SR $repo, $id){
        $sap = $repo->find($id);        
        return view('sap::form',compact('sap'));
    }

    public function update($id, SCR $request, SR $repo){
        $sap = $repo->find($id);
        $sap->update(['name'=>$request->name, 'code'=>$request->code]);
        Session::flash('success', 'The '.$this->entity.' has been updated successfully');
        return redirect()->route('saps.index');
    }

    public function destroy(SR $repo, $id){
        $repo->destroy($id);
        Session::flash('success', 'The '.$this->entity.' has been deleted successfully');
        return redirect()->route('saps.index');
    }
}

Modules/Sap/Resources/views/form.blade.php
@extends('backend.master') 
@section('content')
<div class="row">
    <div class="col-md-9">
        {{-- Start Form --}} 
    @if(isset($sap->id))
    <form action="{{route('saps.update',['id'=>$sap->id])}}" class="card" method="POST">
        {{method_field('PUT')}}
    @else
    <form action="{{route('saps.store')}}" class="card" method="POST">
    @endif
        @csrf
            @cardHeader
                @slot('card_title') Sap Modules @endslot
            @endcardHeader                
        @cardBody                                               
            @formGroup(['form_label'=>'SAP Module Name'])
                <input type="text" class="form-control" name="name" value="{{old('name',$sap->name ?? null)}}">   
            @endformGroup
            @formGroup(['form_label'=>'SAP Module Codename'])
                <input type="text" class="form-control" name="code" value="{{old('name',$sap->code ?? null)}}">   
            @endformGroup
            @formGroup(['form_label'=>''])
                
                <button type="submit" class="btn btn-md btn-primary">
                    <i class="fe {{isset($sap) ? 'fe-edit':'fe-save'}}"></i> {{isset($sap) ? 'Update':'Create'}}           
                </button>
            <a href="{{route('saps.index')}}" class="btn btn-md btn-secondary">Back</a>  
            @endformGroup
        @endcardBody
    </form>
    </div>
</div>
@endsection

Modules/Sap/Resources/views/index.blade.php
@extends('backend.master')

@section('content')
@card
@cardHeader
    @slot('card_title')<i class="fe fe-codepen"></i> Sap Modules @endslot
    @cardOptions
    <a class="btn btn-secondary btn-sm">Total: {{ $results->count() }} {{ str_plural('Sap Module', $results->count()) }}</a>

    @can('add_saps')
    <a href="{{ route('saps.create') }}" class="btn btn-primary btn-sm text-white"> <i class=""></i> Create</a> 
    @endcan 
    @endcardOptions
@endcardHeader

@cardBody
<div class="table-responsive">
    @table(['class'=>'table table-vcenter card-table text-nowrap table-striped', 'id'=>'datatable'])
        <thead>
            <th>#</th>
            <th>Name</th>
            <th>Code</th>            
            @can('edit_saps', 'delete_saps')
            <th class="text-center">Actions</th>
            @endcan
        </thead>
        <tbody>
           @foreach($results as $key => $result)
        <tr>

            <td>{{ ++$key }}</td>
            <td>{{ $result->name }}</td>
            <td>{{ $result->code }}</td>            
        
            @can('edit_saps')
            <td class="text-center">
                @include('shared._actions', [ 'entity' => 'saps', 'id' => $result->id ])
            </td>
            @endcan
            
        </tr>
        @endforeach             
        </tbody>
    @endtable
</div>
@endcardBody
@endcard    
@stop
@include('asset-partials.datatables')