Modules/Application/Http/routes.php
<?php

Route::group(['middleware' => 'web','namespace' => 'Modules\Application\Http\Controllers'], function()
{
    Route::resource('applications', 'ApplicationsController');
});

Modules/Application/Entities/Application.php
<?php

namespace Modules\Application\Entities;

use Illuminate\Database\Eloquent\Model;
use Modules\Ticket\Entities\Ticket;

class Application extends Model
{
    protected $fillable = ['name'];

    public function tickets(){
        return $this->hasMany(Ticket::class);
    }
}

Modules/Application/Http/Controllers/ApplicationController.php
<?php

namespace Modules\Application\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;

class ApplicationController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        return view('application::index');
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        return view('application::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function store(Request $request)
    {
    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show()
    {
        return view('application::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @return Response
     */
    public function edit()
    {
        return view('application::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function update(Request $request)
    {
    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy()
    {
    }
}

Modules/Application/Http/Controllers/ApplicationsController.php
<?php

namespace Modules\Application\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use App\Http\Controllers\Controller;
use Session;
use App\Authorizable;
use Illuminate\Support\Facades\Auth;
use Modules\Application\Repositories\AppsRepository as AR;
// use Modules\Application\Http\Requests\DeptsCreateRequest as Request;

class ApplicationsController extends Controller
{
    use Authorizable;

    private $entity;
    protected $model;

    public function __construct(){
        $this->entity = 'Application';                     
    }

    public function index(AR $repo){
        $results = $repo->all();
        return view('application::index',compact('results'));
    }

    public function create(){
        return view('application::form');
    }

    public function show(){

    }

    public function store(Request $request, AR $repo)
    {
        $repo->create(['name'=>$request->name,'email'=>$request->email]);
        Session::flash('success', 'The '.$this->entity.' has been created successfully');
        return redirect()->route('applications.index');
    }

    public function edit(AR $repo, $id){
        $application = $repo->find($id);        
        return view('application::form',compact('application'));
    }

    public function update($id, Request $request, AR $repo){
        $application = $repo->find($id);
        $application->update(['name'=>$request->name, 'email'=>$request->email]);
        Session::flash('success', 'The '.$this->entity.' has been updated successfully');
        return redirect()->back();
    }

    public function destroy(AR $repo, $id){
        $repo->destroy($id);
        Session::flash('success', 'The '.$this->entity.' has been deleted successfully');
        return redirect()->route('applications.index');
    }
}

Modules/Application/Resources/views/form.blade.php
@extends('backend.master') 
@section('content')
<div class="row">
    <div class="col-md-9">
        {{-- Start Form --}} 
    @if(isset($application->id))
    <form action="{{route('applications.update',['id'=>$application->id])}}" class="card" method="POST">
        {{method_field('PUT')}}
    @else
    <form action="{{route('applications.store')}}" class="card" method="POST">
    @endif
        @csrf
            @cardHeader
                @slot('card_title') Applications @endslot
            @endcardHeader                
        @cardBody                                               
            @formGroup(['form_label'=>'Application Name'])
                <input type="text" class="form-control" name="name" value="{{old('name',$application->name ?? null)}}">   
            @endformGroup           
            @formGroup(['form_label'=>''])
                
                <button type="submit" class="btn btn-md btn-primary">
                        <i class="fe {{isset($application) ? 'fe-edit':'fe-save'}}"></i> {{isset($application) ? 'Update':'Create'}}
                </button>
            <a href="{{route('applications.index')}}" class="btn btn-md btn-secondary">Back</a>  
            @endformGroup
        @endcardBody
    </form>
    </div>
</div>
@endsection

Modules/Application/Resources/views/index.blade.php
@extends('backend.master')

@section('content')
@card
@cardHeader
    @slot('card_title')<i class="fe fe-layout"></i> Applications @endslot
    @cardOptions
    <a class="btn btn-secondary btn-sm">Total: {{ $results->count() }} {{ str_plural('Application', $results->count()) }}</a>

    @can('add_applications')
    <a href="{{ route('applications.create') }}" class="btn btn-primary btn-sm text-white"> <i class=""></i> Create</a> 
    @endcan 
    @endcardOptions
@endcardHeader

@cardBody
<div class="table-responsive">
    @table(['class'=>'table table-vcenter card-table text-nowrap table-striped ', 'id'=>'datatable'])
        <thead>
            <th>#</th>
            <th>Name</th>                      
            @can('edit_applications', 'delete_applications')
            <th class="text-center">Actions</th>
            @endcan
        </thead>
        <tbody>
           @foreach($results as $key => $result)
        <tr>

            <td>{{ ++$key }}</td>
            <td>{{ $result->name }}</td>                             
            @can('edit_applications')
            <td class="text-center">
                @include('shared._actions', [ 'entity' => 'applications', 'id' => $result->id ])
            </td>
            @endcan
            
        </tr>
        @endforeach             
        </tbody>
    @endtable
</div>
@endcardBody
@endcard    
@stop
@include('asset-partials.datatables')